---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

Project website for benchmarking methods for single-cell DE methods. 

* Initial evaluations using PBMC dataset
    * Objectives:
        + Performances undering large sample size (e.g., 50/group, 250/group)
        + Focusing on generic methods: not yet tailored methods for single-cell data
    * Effect size, power and sample size [RESULTS](eval_initial.html)
    * Power and false discovery rate: betasd=1, 1K genes drawn randomly, 10% true effects [RESULTS](eval_initial_power.html)
    * Type I error: betasd=1, 1K genes drawn randomly [RESULTS](eval_initial_type1.html)    

* Evaluation using GTEx lung data
    * Objective:
        + Do bulk methods perform as expected in bulk data?
        + Performance under small to large sample size (e.g., 5, 10, 50, 250)
    * Type I error: betasd=1, 1K genes drawn randomly [RESULTS](gtex_type1.html)    
    * Power and false discovery rate: betasd=1, 1K genes drawn randomly, 10% true effects [RESULTS](gtex_power.html)
    
    
* [Data curation procedure](../dsc/data/README.md).
    * 10x Genomics PBMC dataset
    * GTEx lung samples

---

## One-time investigations

* Replicate results in Van den Berge et al., 2018
    * Curate PBMC dataset using [their code](pbmc_berge_null.html)
    * Simulate scRNA-seq data with signals using [their code](sim_power_berge_pbmc.html)
    
    


    

